### ISSUE TITLE
OSError: libode.so.8: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Jushan-Randy-Chen** [PKU-MACDLab/IMPC-OB#1]
Hi,

I followed the installation steps but encountered some error while running `python3 test.py`:

```
Traceback (most recent call last):
  File "/home/randychen233/projects/ICON_lab/IMPC-OB/src/test.py", line 2, in <module>
    from        run         import *
  File "/home/randychen233/projects/ICON_lab/IMPC-OB/src/run.py", line 2, in <module>
    from uav import *
  File "/home/randychen233/projects/ICON_lab/IMPC-OB/src/uav.py", line 5, in <module>
    from path_planning import *
  File "/home/randychen233/projects/ICON_lab/IMPC-OB/src/path_planning.py", line 4, in <module>
    from ompl import util as ou
  File "/home/randychen233/projects/ICON_lab/IMPC-OB/src/ompl/util/__init__.py", line 3, in <module>
    dll_loader('ompl', dirname(abspath(__file__)))
  File "/home/randychen233/projects/ICON_lab/IMPC-OB/src/ompl/__init__.py", line 17, in dll_loader
    ctypes.CDLL(fname, ctypes.RTLD_GLOBAL)
  File "/home/randychen233/anaconda3/envs/ICON_lab/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libode.so.8: cannot open shared object file: No such file or directory

```

I wonder how I can install this missing file?

**Comment by HauserDong** [comment]
> Hi,
> 
> I followed the installation steps but encountered some error while running `python3 test.py`:
> 
> ```
> Traceback (most recent call last):
>   File "/home/randychen233/projects/ICON_lab/IMPC-OB/src/test.py", line 2, in <module>
>     from        run         import *
>   File "/home/randychen233/projects/ICON_lab/IMPC-OB/src/run.py", line 2, in <module>
>     from uav import *
>   File "/home/randychen233/projects/ICON_lab/IMPC-OB/src/uav.py", line 5, in <module>
>     from path_planning import *
>   File "/home/randychen233/projects/ICON_lab/IMPC-OB/src/path_planning.py", line 4, in <module>
>     from ompl import util as ou
>   File "/home/randychen233/projects/ICON_lab/IMPC-OB/src/ompl/util/__init__.py", line 3, in <module>
>     dll_loader('ompl', dirname(abspath(__file__)))
>   File "/home/randychen233/projects/ICON_lab/IMPC-OB/src/ompl/__init__.py", line 17, in dll_loader
>     ctypes.CDLL(fname, ctypes.RTLD_GLOBAL)
>   File "/home/randychen233/anaconda3/envs/ICON_lab/lib/python3.10/ctypes/__init__.py", line 374, in __init__
>     self._handle = _dlopen(self._name, mode)
> OSError: libode.so.8: cannot open shared object file: No such file or directory
> ```
> 
> I wonder how I can install this missing file?

@RandyChen233 I also encounter issues when running `python3 test.py`. I find a way to solve my issues. Maybe you can have a try.
If you are using conda when running the code, make sure you have **python version 3.9** and follow the suggested version of other packages. I used to use 3.11, but fail to run the test code. When I delete my conda environment and set up a new one with 3.9, I finally succeed.

**Comment by CYDXYYJ** [comment]
> > Hi,
> > I followed the installation steps but encountered some error while running `python3 test.py`:
> > ```
> > Traceback (most recent call last):
> >   File "/home/randychen233/projects/ICON_lab/IMPC-OB/src/test.py", line 2, in <module>
> >     from        run         import *
> >   File "/home/randychen233/projects/ICON_lab/IMPC-OB/src/run.py", line 2, in <module>
> >     from uav import *
> >   File "/home/randychen233/projects/ICON_lab/IMPC-OB/src/uav.py", line 5, in <module>
> >     from path_planning import *
> >   File "/home/randychen233/projects/ICON_lab/IMPC-OB/src/path_planning.py", line 4, in <module>
> >     from ompl import util as ou
> >   File "/home/randychen233/projects/ICON_lab/IMPC-OB/src/ompl/util/__init__.py", line 3, in <module>
> >     dll_loader('ompl', dirname(abspath(__file__)))
> >   File "/home/randychen233/projects/ICON_lab/IMPC-OB/src/ompl/__init__.py", line 17, in dll_loader
> >     ctypes.CDLL(fname, ctypes.RTLD_GLOBAL)
> >   File "/home/randychen233/anaconda3/envs/ICON_lab/lib/python3.10/ctypes/__init__.py", line 374, in __init__
> >     self._handle = _dlopen(self._name, mode)
> > OSError: libode.so.8: cannot open shared object file: No such file or directory
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I wonder how I can install this missing file?
> 
> @RandyChen233 I also encounter issues when running `python3 test.py`. I find a way to solve my issues. Maybe you can have a try. If you are using conda when running the code, make sure you have **python version 3.9** and follow the suggested version of other packages. I used to use 3.11, but fail to run the test code. When I delete my conda environment and set up a new one with 3.9, I finally succeed.

Thanks Bro, well done.
